### ISSUE TITLE
On chain C# SDKs aren't working

### ISSUE THREAD

**Issue by lock9** [CityOfZion/cpm#26]
Hi,

It seems that the c# code generated by CPM is not valid (malformed):
<img width="955" alt="Screenshot 2024-01-17 at 15 10 48" src="https://github.com/CityOfZion/cpm/assets/38396062/ae08cc60-3c63-4127-be55-37b315b61fd8">

It seems that there are problems with import too:
<img width="797" alt="Screenshot 2024-01-17 at 15 11 19" src="https://github.com/CityOfZion/cpm/assets/38396062/ea0c38fc-8f18-4134-9e91-b76c7c80372f">

**Comment by ixje** [comment]
I'm not getting any errors here, but I'm guessing 
```
using System.Numerics;
```
is missing? Can you add that and see if that solves your issues?

**Comment by lock9** [comment]
Hello,
It fixes one error, the imports one. However, the file is malformed. The methods are missing the closing bracket:

<img width="949" alt="Screenshot 2024-01-19 at 12 27 09" src="https://github.com/CityOfZion/cpm/assets/38396062/25fedca7-d7f5-4232-a3c9-5ea2350256f2">

**Comment by ixje** [comment]
oh I see now. You can add the closing brace between these 2 lines
https://github.com/CityOfZion/cpm/blob/0445b4dcd26459d383c8ba8439c54d5dc695668d/generators/csharp/onchain.go#L21-L22

Let me know if that works, and if it does please PR ;)
